github.com:
    users:
        prinsgras:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: prinsgras
